<?php
namespace Windsurfdb\MatosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BoardSpecRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoardSpecRepository extends EntityRepository
{
	public function findByBoard($board) {
		$qb = $this
			->createQueryBuilder('a')
			->where('a.board = :board')
			->leftJoin('a.programmes', 'c')
			->addSelect('c')
			->setParameter('board', $board->getId())
		;

		return $qb
			->getQuery()
			->getResult()
		;
	}
	public function findByBoards($boards) {
		$qb = $this->createQueryBuilder('a');
		$qb ->where($qb->expr()->in('a.board', $boards))
			->leftJoin('a.programmes', 'c')
			->addSelect('c')
		;

		return $qb
			->getQuery()
			->getResult()
		;
	}
	public function findOneById($id) {
		$qb = $this
			->createQueryBuilder('a')
			->where('a.id = :id')
			->leftJoin('a.programmes', 'c')
			->addSelect('c')
			->setParameter('id', $id)
		;

		return $qb
			->getQuery()
			->getOneOrNullResult()
		;
	}
}
