<?php
namespace Windsurfdb\MatosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MarqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarqueRepository extends EntityRepository
{
	public function findByType($type) {
		$qb = $this
			->createQueryBuilder('a')
			->where('a.type LIKE :type')
			//->where("FIND_IN_SET(:type, `a.type`)")
			->setParameter('type', '%'.$type.'%')
		;
		return $qb
			->getQuery()
			->getResult()
		;
	}
}
